Allow package separate extraction

diff --git a/src/lib/bashLib-0.16/modules b/src/lib/bashLib-0.16/modules
--- a/src/lib/bashLib-0.16/modules
+++ b/src/lib/bashLib-0.16/modules
@@ -35,6 +35,60 @@ modules::install::repo_type() {
     return 255
 }
 
+modules::install::extract_temp() {
+    local _url="${1?Need to provide a url}"
+    local _branch="${2}"
+    local _tempdir
+
+    if ! _tempdir="$(mktemp --directory --quiet)"
+    then
+        logging::error "Cannot create temporary folder"
+        return 255
+    fi
+
+    local _mode="$(modules::install::repo_type "${_url}")"
+
+    case "${_mode}" in
+        hg)
+            if ! hg clone "${_url}" "${_tempdir}" --branch="${_branch:-default}" >/dev/null 2>&1
+            then
+                logging::error "Failed to checkout repo '${_url}' with branch ${_branch:-default}"
+                rm -rf "${_tempdir}"
+                return 254
+            fi
+            ;;
+
+        git)
+            if ! git clone "${_url}" "${_tempdir}" --branch="${_branch:-master}" >/dev/null 2>&1
+            then
+                logging::error "Failed to checkout repo '${_url}' with branch ${_branch:-master}"
+                rm -rf "${_tempdir}"
+                return 253
+            fi
+            ;;
+
+        pip)
+            local _pypi_package="$(echo "${_url}" | sed -e 's/^pip[\:]//g')"
+
+            if ! (cd "${_tempdir}" && pip download "${_pypi_package}")
+            then
+                logging::error "Failed to install python package '${_pypi_package}'"
+                rm -rf "${_tempdir}"
+                return 252
+            fi
+            ;;
+
+        *)
+            logging::error "Unknown repo type ${_url}"
+            rm -rf "${_tempdir}"
+            return 255
+            ;;
+    esac
+
+    logging::info "Extracted '${_url}' into '${_tempdir}' with mode ${_mode}"
+    echo "${_mode} ${_tempdir}"
+}
+
 modules::install::install() {
     cleanup() {
         local _level="${1:-0}"
@@ -45,83 +99,67 @@ modules::install::install() {
     local _url="${1?Need to provide a url}"
     local _branch="${2}"
     local _tempdir
+    local _response
+    local _mode
 
-    if ! _tempdir="$(mktemp --directory --quiet)"
+    if ! _response="$(modules::install::extract_temp "${_url}" "${_branch}")"
     then
-        logging::error "Cannot create temporary folder"
-        cleanup 0
+        logging::error "Failed to extract '${_url}'"
         return 255
     fi
 
-    case "$(modules::install::repo_type "${_url}")" in
-        hg)
-            if ! hg clone "${_url}" "${_tempdir}" --branch="${_branch:-default}" >/dev/null 2>&1
-            then
-                logging::error "Failed to checkout repo '${_url}' with branch ${_branch:-default}"
-                cleanup 0
-                return 254
-            fi
-            ;;
+    read _mode _tempdir <<< "${_response}"
 
-        git)
-            if ! git clone "${_url}" "${_tempdir}" --branch="${_branch:-master}" >/dev/null 2>&1
-            then
-                logging::error "Failed to checkout repo '${_url}' with branch ${_branch:-master}"
-                cleanup 0
-                return 253
-            fi
-            ;;
-
-        pip)
-            local _pypi_package="$(echo "${_url}" | sed -e 's/^pip[\:]//g')"
-
-            if ! pip install "${_pypi_package}"
-            then
-                logging::error "Failed to install python package '${_pypi_package}'"
-                cleanup 0
-                return 252
-            fi
-            ;;
-
-        *)
-            logging::error "Unknown repo type ${_url}"
-            cleanup 0
-            return 255
-            ;;
-    esac
-
-    if ! pushd "${_tempdir}" >/dev/null 2>&1
+    if [ -z "${_tempdir}" ]
+    then
+        logging::error "No temporary folder was created"
+        return 255
+    elif ! pushd "${_tempdir}" >/dev/null 2>&1
     then
         logging::error "Couldn't use temporary folder '${_tempdir}'"
-        cleanup 0
-        return 252
+        rm -rf "${_tempdir}"
+        return 255
     fi
 
-    if [ -f Makefile ]
+    success=true
+
+    if [ "${_mode}" = "pip" ]
+    then
+        local _pypi_package="$(echo "${_url}" | sed -e 's/^pip[\:]//g')"
+
+        if ! pip install --findlinks . "${_pypi_package}"
+        then
+            logging::error "Failed to install python package '${_pypi_package}'"
+            success=false
+        fi
+    elif [ -f Makefile ]
     then
         if ! make install
         then
             logging::error "Failed running make on '${_url}'"
-            cleanup 1
-            return 251
+            success=false
         fi
     elif [ -f setup.py ]
     then
         if ! "$(virtualenv::python)" setup.py install
         then
             logging::error "Couldn't install python package from '${_url}'"
-            cleanup 1
-            return 251
+            success=false
         fi
     else
         logging::error "Unknown installation mechanism in ${_url}"
-        cleanup 1
-        return 251
+        success=false
     fi
 
-    logging::info "Successfully installed branch '${_branch}' from package '${_url}'"
-    cleanup 1
-    return 0
+    rm -rf "${_tempdir}"
+
+    if $success
+    then
+        logging::info "Successfully installed branch '${_branch}' from package '${_url}'"
+        return 0
+    else
+        return 255
+    fi
 }
 
 modules::install::git() {
