added property module

diff --git a/src/lib/bashLib-0.20/subcommands/container-group b/src/lib/bashLib-0.20/subcommands/container-group
--- a/src/lib/bashLib-0.20/subcommands/container-group
+++ b/src/lib/bashLib-0.20/subcommands/container-group
@@ -15,19 +15,21 @@ logging::set_severity info
 #===================================================================================
 showhelp() {
     local _synopsis="
-        Maintain running containers
+        Maintain grouped services
     "
 
     local -A _keywords=(
-        [status]="List container states"
-        [start]="Start a container"
-        [stop]="Stop a container"
-        [rebuild]="Rebuild a container"
-        [cleanup]="Delete a container"
-        [instance:]="Specify a container instance"
-        [image:]="Specify an image name"
-        [commit]="Save a container instance as an image"
-        [tag:]="Specify an image tag (default: latest)"
+        [debug]="Expose debug level logging"
+        [info]="Expose normal level logging"
+        [warning]="Expose error level logging"
+        [error]="Expose error level logging"
+        [fatal]="Expose fatal error level logging"
+        [groups]="Produce a list of known service groups"
+        [group]="Select a specific group"
+        [start]="Start instances for the specified group"
+        [stop]="Stop instances for the specified group"
+        [instances]="Produce a list of instances for a known service group"
+        [status]="Produce the instance statuses for a known service group"
         [version]="Produce the version string"
         [help]="Display instructions"
     )
@@ -37,7 +39,7 @@ showhelp() {
 
     local _contents="$(
         echo "${_terms}" | awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
-        echo -en "${_synopsis:+\n\n}"
+        echo -en "${_synopsis:+\n}"
         echo "${_synopsis}" | sed -e 's/^[ ]*//g' -e '/^[ ]*$/d'
 
         echo "${_terms}" | {
@@ -55,7 +57,7 @@ showhelp() {
         }
     )"
 
-    echo "Usage: $0 ${_contents}" >&2
+    echo -e "Usage: $0 ${_contents}\n" >&2
 }
 
 #===================================================================================
@@ -63,7 +65,7 @@ showhelp() {
 #       will cause the first non option parameter to be discarded. Here, we just
 #       use -h (help)
 #===================================================================================
-long_options="help,version,debug,info,warning,error,fatal,start,stop,rebuild,cleanup,status,instance:,name:,image:,tag:,console,commit"
+long_options="help,version,debug,info,warning,error,fatal,groups,group:,instances,start,stop,status"
 
 OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")
 
@@ -80,37 +82,48 @@ eval set -- "$OPTION_TEMP"
 # NOTE: The command line parameters are available for scripts which
 #       source this file.
 #===================================================================================
-action=
-image=
-tag=
-instance_name=
+selected_group=Default
 
 while true
 do
     case "$1" in
+        --start|--stop)
+            action="$(echo "${1}" | sed -e 's/^[-]*//g')"
+            shift
+            ;;
+
         --debug|--info|--warning|--error|--fatal)
             logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
             shift
             ;;
 
-        --start|--stop|--rebuild|--cleanup|--status|--console|--commit)
-            action="$(echo "${1}" | sed -e 's/^[-]*//g')"
-            shift
-            ;;
+        --group)
+            if [ -z "${2}" ]
+            then
+                echo "${selected_group}"
+                exit 0
+            else
+                selected_group="${2}"
+            fi
 
-        --image)
-            image="$2"
             shift 2
             ;;
 
-        --instance|--name)
-            instance_name="$2"
-            shift 2
+        --groups)
+            container::group::groups
+            exit $?
             ;;
 
-        --tag)
-            tag="$2"
-            shift 2
+        --status)
+            container::group::instances group="${selected_group}" |
+            tabular::apply 'echo "${_column_id},${_column_state},${_column_service}"' "$(container::instance::separator)"
+            exit $?
+            ;;
+
+        --instances)
+            container::group::instances group="${selected_group}" |
+            tabular::apply 'echo "${_column_service}"' "$(container::instance::separator)"
+            exit $?
             ;;
 
         --version)
@@ -134,39 +147,12 @@ done
 #                             Perform selected action
 #===================================================================================
 case "${action}" in
-    commit)
-        container::instance::save_image instance="${instance_name}" image="${image}" tag="${tag}"
-        exit $?
-        ;;
-
     start)
-        container::instance::start instance="${instance_name}" image="${image}" tag="${tag}"
-        exit $?
-        ;;
-
-    rebuild)
-        container::instance::rebuild instance="${instance_name}" image="${image}" tag="${tag}"
-        exit $?
-        ;;
-
-    status)
-        container::instance::instances instance="${instance_name}"
-        exit $?
-        ;;
-
-    cleanup)
-        container::instance::cleanup instance="${instance_name}"
-        exit $?
+        container::group::start group="${selected_group}"
         ;;
 
     stop)
-        container::instance::stop instance="${instance_name}"
-        exit $?
-        ;;
-
-    console)
-        container::instance::console instance="${instance_name}"
-        exit $?
+        container::group::stop group="${selected_group}"
         ;;
 
     *)
diff --git a/src/lib/bashLib-0.20/subcommands/container-instance b/src/lib/bashLib-0.20/subcommands/container-instance
--- a/src/lib/bashLib-0.20/subcommands/container-instance
+++ b/src/lib/bashLib-0.20/subcommands/container-instance
@@ -15,14 +15,24 @@ logging::set_severity info
 #===================================================================================
 showhelp() {
     local _synopsis="
-        Maintain services list
+        Maintain running containers
     "
 
     local -A _keywords=(
-        [list]="Provide the list of registered services"
-        [path]="Path for the service registry store"
-        [register]="Register a service and/or return the port"
-        [deregister]="Deregister a service"
+        [debug]="Expose debug level logging"
+        [info]="Expose normal level logging"
+        [warning]="Expose error level logging"
+        [error]="Expose error level logging"
+        [fatal]="Expose fatal error level logging"
+        [status]="List container states"
+        [start]="Start a container"
+        [stop]="Stop a container"
+        [rebuild]="Rebuild a container"
+        [cleanup]="Delete a container"
+        [instance:]="Specify a container instance"
+        [image:]="Specify an image name"
+        [commit]="Save a container instance as an image"
+        [tag:]="Specify an image tag (default: latest)"
         [version]="Produce the version string"
         [help]="Display instructions"
     )
@@ -32,7 +42,7 @@ showhelp() {
 
     local _contents="$(
         echo "${_terms}" | awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
-        echo -en "${_synopsis:+\n}"
+        echo -en "${_synopsis:+\n\n}"
         echo "${_synopsis}" | sed -e 's/^[ ]*//g' -e '/^[ ]*$/d'
 
         echo "${_terms}" | {
@@ -50,7 +60,7 @@ showhelp() {
         }
     )"
 
-    echo "Usage: $0 ${_contents}" >&2
+    echo -e "Usage: $0 ${_contents}\n" >&2
 }
 
 #===================================================================================
@@ -58,7 +68,7 @@ showhelp() {
 #       will cause the first non option parameter to be discarded. Here, we just
 #       use -h (help)
 #===================================================================================
-long_options="help,version,debug,info,warning,error,fatal,list,path::,register:,deregister:"
+long_options="help,version,debug,info,warning,error,fatal,start,stop,rebuild,cleanup,status,instance:,name:,image:,tag:,console,commit"
 
 OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")
 
@@ -75,6 +85,11 @@ eval set -- "$OPTION_TEMP"
 # NOTE: The command line parameters are available for scripts which
 #       source this file.
 #===================================================================================
+action=
+image=
+tag=
+instance_name=
+
 while true
 do
     case "$1" in
@@ -83,30 +98,24 @@ do
             shift
             ;;
 
-        --path)
-            if [ -z "${2}" ]
-            then
-                network::services::path
-            else
-                network::services::path "${2}"
-            fi
+        --start|--stop|--rebuild|--cleanup|--status|--console|--commit)
+            action="$(echo "${1}" | sed -e 's/^[-]*//g')"
+            shift
+            ;;
 
+        --image)
+            image="$2"
             shift 2
             ;;
 
-        --register)
-            network::services::registration service="${2}"
-            exit $?
+        --instance|--name)
+            instance_name="$2"
+            shift 2
             ;;
 
-        --deregister)
-            network::services::deregister service="${2}"
-            exit $?
-            ;;
-
-        --list)
-            network::services
-            exit $?
+        --tag)
+            tag="$2"
+            shift 2
             ;;
 
         --version)
@@ -125,3 +134,47 @@ do
             ;;
     esac
 done
+
+#===================================================================================
+#                             Perform selected action
+#===================================================================================
+case "${action}" in
+    commit)
+        container::instance::save_image instance="${instance_name}" image="${image}" tag="${tag}"
+        exit $?
+        ;;
+
+    start)
+        container::instance::start instance="${instance_name}" image="${image}" tag="${tag}"
+        exit $?
+        ;;
+
+    rebuild)
+        container::instance::rebuild instance="${instance_name}" image="${image}" tag="${tag}"
+        exit $?
+        ;;
+
+    status)
+        container::instance::instances instance="${instance_name}"
+        exit $?
+        ;;
+
+    cleanup)
+        container::instance::cleanup instance="${instance_name}"
+        exit $?
+        ;;
+
+    stop)
+        container::instance::stop instance="${instance_name}"
+        exit $?
+        ;;
+
+    console)
+        container::instance::console instance="${instance_name}"
+        exit $?
+        ;;
+
+    *)
+        logging::fatal "Unknown or invalid action '${action}'"
+        ;;
+esac
diff --git a/src/lib/bashLib-0.20/subcommands/service_registry b/src/lib/bashLib-0.20/subcommands/service_registry
--- a/src/lib/bashLib-0.20/subcommands/service_registry
+++ b/src/lib/bashLib-0.20/subcommands/service_registry
@@ -15,16 +15,19 @@ logging::set_severity info
 #===================================================================================
 showhelp() {
     local _synopsis="
-        Maintain grouped services
+        Maintain services list
     "
 
     local -A _keywords=(
-        [groups]="Produce a list of known service groups"
-        [group]="Select a specific group"
-        [start]="Start instances for the specified group"
-        [stop]="Stop instances for the specified group"
-        [instances]="Produce a list of instances for a known service group"
-        [status]="Produce the instance statuses for a known service group"
+        [debug]="Expose debug level logging"
+        [info]="Expose normal level logging"
+        [warning]="Expose error level logging"
+        [error]="Expose error level logging"
+        [fatal]="Expose fatal error level logging"
+        [list]="Provide the list of registered services"
+        [path]="Path for the service registry store"
+        [register]="Register a service and/or return the port"
+        [deregister]="Deregister a service"
         [version]="Produce the version string"
         [help]="Display instructions"
     )
@@ -52,7 +55,7 @@ showhelp() {
         }
     )"
 
-    echo "Usage: $0 ${_contents}" >&2
+    echo -e "Usage: $0 ${_contents}\n" >&2
 }
 
 #===================================================================================
@@ -60,7 +63,7 @@ showhelp() {
 #       will cause the first non option parameter to be discarded. Here, we just
 #       use -h (help)
 #===================================================================================
-long_options="help,version,debug,info,warning,error,fatal,groups,group:,instances,start,stop,status"
+long_options="help,version,debug,info,warning,error,fatal,list,path::,register:,deregister:"
 
 OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")
 
@@ -77,47 +80,37 @@ eval set -- "$OPTION_TEMP"
 # NOTE: The command line parameters are available for scripts which
 #       source this file.
 #===================================================================================
-selected_group=Default
-
 while true
 do
     case "$1" in
-        --start|--stop)
-            action="$(echo "${1}" | sed -e 's/^[-]*//g')"
-            shift
-            ;;
-
         --debug|--info|--warning|--error|--fatal)
             logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
             shift
             ;;
 
-        --group)
+        --path)
             if [ -z "${2}" ]
             then
-                echo "${selected_group}"
-                exit 0
+                network::services::path
             else
-                selected_group="${2}"
+                network::services::path "${2}"
             fi
 
             shift 2
             ;;
 
-        --groups)
-            container::group::groups
+        --register)
+            network::services::registration service="${2}"
             exit $?
             ;;
 
-        --status)
-            container::group::instances group="${selected_group}" |
-            tabular::apply 'echo "${_column_id},${_column_state},${_column_service}"' "$(container::instance::separator)"
+        --deregister)
+            network::services::deregister service="${2}"
             exit $?
             ;;
 
-        --instances)
-            container::group::instances group="${selected_group}" |
-            tabular::apply 'echo "${_column_service}"' "$(container::instance::separator)"
+        --list)
+            network::services
             exit $?
             ;;
 
@@ -137,20 +130,3 @@ do
             ;;
     esac
 done
-
-#===================================================================================
-#                             Perform selected action
-#===================================================================================
-case "${action}" in
-    start)
-        container::group::start group="${selected_group}"
-        ;;
-
-    stop)
-        container::group::stop group="${selected_group}"
-        ;;
-
-    *)
-        logging::fatal "Unknown or invalid action '${action}'"
-        ;;
-esac
